Features/start proj
AndriyKostenko/Fast_API_project pull request #1
Opened 2022-07-05 08:46 UTC by AndriyKostenko

Pull from Features to Beta

2022-07-05 11:01 UTC, Rybasher requested changes
добавь файл .gitignore, у тебя не должно быть .idea и inspectionProfiles на гитхабе

2022-07-05 11:01 UTC, Rybasher commented on main.py
> +    return {'users': users}
добавь пж файл user_routes.py в папку routes, добавь эти ендпоинты туда, скину пример

2022-07-05 11:35 UTC, AndriyKostenko commented on main.py
> +    return {'users': users}
I've included .gitignore and removed others stuff.

2022-07-05 12:13 UTC, Rybasher requested changes

2022-07-05 12:13 UTC, Rybasher commented on routes/user_routes.py
> +from app.main import app
Удали эту строчку и добав `from fastapi import APIRouter`

2022-07-05 12:13 UTC, Rybasher commented on routes/user_routes.py
> +
перед списком добавь 

`route = APIRouter(tags=['users'])`

2022-07-05 12:13 UTC, Rybasher commented on routes/user_routes.py
> +@app.get("/")
теперь вместо app напиши во всех ендпоинтах route

2022-07-06 06:03 UTC, AndriyKostenko commented on routes/user_routes.py
> +@app.get("/")
It's done.

2022-07-06 06:03 UTC, AndriyKostenko commented on routes/user_routes.py
> +
Done.

2022-07-06 06:03 UTC, AndriyKostenko commented on routes/user_routes.py
> +from app.main import app
Done.

2022-07-06 08:40 UTC, Rybasher requested changes
Измени структуру

2022-07-06 08:40 UTC, Rybasher commented on app/main.py
> +
app.include_router(user_routes.route)

2022-07-06 08:40 UTC, Rybasher commented on app/main.py
> +
from app.routes import user_routes

2022-07-06 11:20 UTC, AndriyKostenko commented on app/main.py
> +
Done

2022-07-06 11:20 UTC, AndriyKostenko commented on app/main.py
> +
Done

2022-07-06 12:41 UTC, Rybasher approved these changes

2022-07-06 12:43 UTC, merged