Adding docker-compose file, adding database.py for connecting db
AndriyKostenko/Fast_API_project pull request #3
Opened 2022-07-06 08:29 UTC by AndriyKostenko

Adding docker-compose file, adding database.py for connecting db

2022-07-06 14:29 UTC, Rybasher requested changes
Добавь коннект к бд при запуске приложения

2022-07-06 17:20 UTC, Rybasher requested changes

2022-07-06 17:20 UTC, Rybasher commented on docker-compose.yml
> +
Посмотри как поместить эти 2 сервиса в один нетворк

2022-07-06 17:20 UTC, Rybasher commented on docker-compose.yml
> +      - 8080:8080
Посмотри как добавить волюмы и что это такое

2022-07-07 06:51 UTC, AndriyKostenko commented on docker-compose.yml
> +
Done.

2022-07-07 06:51 UTC, AndriyKostenko commented on docker-compose.yml
> +      - 8080:8080
Done.

2022-07-18 15:05 UTC, merged